### ISSUE TITLE
Possibly unhandled Error: Wrong reservation_id (v3 branch)

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#44]
Possibly unhandled Error: Wrong reservation_id
    at APIClient.Client.parseResponse (.../iron_mq/node_modules/iron_core/lib/client.js:249:21)
    at .../iron_mq/lib/api_client.js:223:16

I think there's a missing Promise.catch or something, because that error is printing out, but not reaching any of my handlers.

**Comment by featalion** [comment]
Cannot reproduce:

```js
q.post("my message", function(err, body) {
   console.log("Error: ", err, "\nBody: ", body);
});
//> Error:  null
//> Body:  6112869851083046914
q.del('6112869851083046914', {reservation_id: 'asdfasdfasdf'}, function(err, body) {
  console.log("Error: ", err, "\nBody: ", body);
});
//> Error:  [Error: Invalid reservation_id]
//> Body:  null
q.del('6112869851083046914', {}, function(err, body) {
  console.log("Error: ", err, "\nBody: ", body);
});
//> Error:  null
//> Body:  { msg: 'Deleted' }
q.post("second message", function(err, body) {
  console.log("Error: ", err, "\nBody: ", body);
});
//> Error:  null
//> Body:  6112873068013551619
q.reserve({}, function(err, body) {
  console.log("Error: ", err, "\nBody: ", body);
});
//> Error:  null
//> Body:  { id: '6112873068013551619',
//>   body: 'second message',
//>   reservation_id: 'd873cc2d12c139c475b24fb44dc65357',
//>   reserved_count: 2 }
q.del('6112873068013551619', {reservation_id: 'd873cc2d12c139c475b24fb44dc65357'},
      function(err, body) {console.log("Error: ", err, "\nBody: ", body);});
//> Error:  null
//> Body:  { msg: 'Deleted' }
```

**Comment by GeoffreyPlitt** [comment]
Shoot, my bad. This was a Promise issue on my side, the stack trace confused me.
