### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by ysadka** [iron-io/iron_mq_node#46]
@sunloverz

```sh
successfully got 100 messages.
dynamodb putitem successful. message ID: 1b973a96-9f7e-46f9-9776-e469e48e8e2a
dynamodb putitem successful. message ID: 6b527e7a-e6e8-497d-a1ab-6a97e2351ce9
dynamodb putitem successful. message ID: 733f5e07-d3b5-483a-aecd-cab022ced858
dynamodb putitem successful. message ID: 2479d131-f602-4773-9f5a-0713ac127969
dynamodb putitem successful. message ID: 1fa29d16-4352-46ca-8090-721345b04025

TypeError: undefined is not a function
    at /mnt/task/node_modules/iron_mq/lib/client.js:295:18
    at APIClient.Client.parseResponse (/mnt/task/node_modules/iron_mq/node_modules/iron_core/lib/client.js:249:18)
    at /mnt/task/node_modules/iron_mq/lib/api_client.js:187:16
    at Request._callback (/mnt/task/node_modules/iron_mq/node_modules/iron_core/lib/client.js:180:20)
    at Request.self.callback (/mnt/task/node_modules/iron_mq/node_modules/iron_core/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/mnt/task/node_modules/iron_mq/node_modules/iron_core/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/mnt/task/node_modules/iron_mq/node_modules/iron_core/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
````

**Comment by sunloverz** [comment]
@ysadka could you please clarify a little bit your issue? What are you doing to get this error?

**Comment by ysadka** [comment]
@sunloverz see gist: https://gist.github.com/ysadka/865e0086e5bbbac4bf84

**Comment by sunloverz** [comment]
@ysadka You should pass an empty options to delete a message as follows:
queue.del('6114870571403623787', {}, function(error, response){});
