### ISSUE TITLE
Uncaught exception while attempting to parse _undefined_ as json (v3 branch)

### ISSUE THREAD

**Issue by kaldimar** [iron-io/iron_mq_node#55]
At odd times, `queue.get()` returns `undefined` and that breaks the call to `JSON.parse(body)` at _lib/api_client.js:60_. A check for valid object literal before calling `JSON.parse` may avoid this uncaught exception, which happens only once every hundreds of queue requests (maybe a race condition on high-traffic queues?)

Stack trace:
```
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /mnt/task/node_modules/iron_mq/lib/api_client.js:60:21
    at Request._callback (/mnt/task/node_modules/iron_mq/node_modules/iron_core/lib/client.js:172:18)
    at self.callback (/mnt/task/node_modules/iron_mq/node_modules/iron_core/node_modules/request/request.js:344:22)
    at Request.emit (events.js:95:17)
    at Request.onRequestError (/mnt/task/node_modules/iron_mq/node_modules/iron_core/node_modules/request/request.js:961:8)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1440:17)
```

**Comment by rdallman** [comment]
thanks. @featalion please take a look

**Comment by kaldimar** [comment]
Any updates on this? We still get the _undefined_ response (which breaks our worker) at random times.

**Comment by treeder** [comment]
Hey @kaldimar , quickest way to get this in would be a pull request.
